//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIVDeck.FFXIVPlugin.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XIVDeck.FFXIVPlugin.Resources.Localization.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} ID {1} has not been unlocked and cannot be used..
        /// </summary>
        internal static string XIVDeck {
            get {
                return ResourceManager.GetString("XIVDeck", resourceCulture);
            }
        }
        
        internal static string StreamDeck {
            get {
                return ResourceManager.GetString("StreamDeck", resourceCulture);
            }
        }
        
        internal static string XIVDeckPlugin_Name {
            get {
                return ResourceManager.GetString("XIVDeckPlugin_Name", resourceCulture);
            }
        }
        
        internal static string PlayerNotLoggedInException_Message {
            get {
                return ResourceManager.GetString("PlayerNotLoggedInException_Message", resourceCulture);
            }
        }
        
        internal static string ActionLockedException_Message {
            get {
                return ResourceManager.GetString("ActionLockedException_Message", resourceCulture);
            }
        }
        
        internal static string ActionNotFoundException_Message {
            get {
                return ResourceManager.GetString("ActionNotFoundException_Message", resourceCulture);
            }
        }
        
        internal static string MissingCommandException_Message {
            get {
                return ResourceManager.GetString("MissingCommandException_Message", resourceCulture);
            }
        }
        
        internal static string UnsafeCommandException_Message {
            get {
                return ResourceManager.GetString("UnsafeCommandException_Message", resourceCulture);
            }
        }
        
        internal static string ActionTypeNotFoundException_Message {
            get {
                return ResourceManager.GetString("ActionTypeNotFoundException_Message", resourceCulture);
            }
        }
        
        internal static string ClassJobService_ClassLessThan1Error {
            get {
                return ResourceManager.GetString("ClassJobService_ClassLessThan1Error", resourceCulture);
            }
        }
        
        internal static string ClassJobService_InvalidClassIdError {
            get {
                return ResourceManager.GetString("ClassJobService_InvalidClassIdError", resourceCulture);
            }
        }
        
        internal static string ClassJobService_NoGearsetForClassError {
            get {
                return ResourceManager.GetString("ClassJobService_NoGearsetForClassError", resourceCulture);
            }
        }
        
        internal static string HotbarService_InvalidHotbarIdError {
            get {
                return ResourceManager.GetString("HotbarService_InvalidHotbarIdError", resourceCulture);
            }
        }
        
        internal static string HotbarService_NormalHotbarInvalidSlotError {
            get {
                return ResourceManager.GetString("HotbarService_NormalHotbarInvalidSlotError", resourceCulture);
            }
        }
        
        internal static string HotbarService_CrossHotbarInvalidSlotError {
            get {
                return ResourceManager.GetString("HotbarService_CrossHotbarInvalidSlotError", resourceCulture);
            }
        }
        
        internal static string EmoteStrategy_EmoteLockedError {
            get {
                return ResourceManager.GetString("EmoteStrategy_EmoteLockedError", resourceCulture);
            }
        }
        
        internal static string FixedCommandStrategy_ActionNotFoundError {
            get {
                return ResourceManager.GetString("FixedCommandStrategy_ActionNotFoundError", resourceCulture);
            }
        }
        
        internal static string FixedCommandStrategy_IllegalActionError {
            get {
                return ResourceManager.GetString("FixedCommandStrategy_IllegalActionError", resourceCulture);
            }
        }
        
        internal static string FixedCommandStrategy_SheetNotFoundError {
            get {
                return ResourceManager.GetString("FixedCommandStrategy_SheetNotFoundError", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_SafeModeDisabledWarning {
            get {
                return ResourceManager.GetString("SettingsWindow_SafeModeDisabledWarning", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_GitHubLink {
            get {
                return ResourceManager.GetString("SettingsWindow_GitHubLink", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_ApplyButton {
            get {
                return ResourceManager.GetString("SettingsWindow_ApplyButton", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_APIPort {
            get {
                return ResourceManager.GetString("SettingsWindow_APIPort", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_TransportType {
            get {
                return ResourceManager.GetString("SettingsWindow_TransportType", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_TransportType_Help {
            get {
                return ResourceManager.GetString("SettingsWindow_TransportType_Help", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_TransportType_WebSocket {
            get {
                return ResourceManager.GetString("SettingsWindow_TransportType_WebSocket", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_TransportType_UnixDomainSocket {
            get {
                return ResourceManager.GetString("SettingsWindow_TransportType_UnixDomainSocket", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_TransportType_NamedPipe {
            get {
                return ResourceManager.GetString("SettingsWindow_TransportType_NamedPipe", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_ListenIP {
            get {
                return ResourceManager.GetString("SettingsWindow_ListenIP", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_APIPort_Help {
            get {
                return ResourceManager.GetString("SettingsWindow_APIPort_Help", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_PipeName {
            get {
                return ResourceManager.GetString("SettingsWindow_PipeName", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_SocketPath {
            get {
                return ResourceManager.GetString("SettingsWindow_SocketPath", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_SocketPath_Native {
            get {
                return ResourceManager.GetString("SettingsWindow_SocketPath_Native", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_TransportFallbackNotice {
            get {
                return ResourceManager.GetString("SettingsWindow_TransportFallbackNotice", resourceCulture);
            }
        }
        
        internal static string UpdateNotifier_ForcedUpdate_Headline {
            get {
                return ResourceManager.GetString("UpdateNotifier_ForcedUpdate_Headline", resourceCulture);
            }
        }
        
        internal static string Common_OpenGitHubDownloadButton {
            get {
                return ResourceManager.GetString("Common_OpenGitHubDownloadButton", resourceCulture);
            }
        }
        
        internal static string Common_OpenSettingsButton {
            get {
                return ResourceManager.GetString("Common_OpenSettingsButton", resourceCulture);
            }
        }
        
        internal static string TransportManager_RetryButton {
            get {
                return ResourceManager.GetString("TransportManager_RetryButton", resourceCulture);
            }
        }
        
        internal static string UpdateNotifier_ForcedUpdate_ProblemDescription {
            get {
                return ResourceManager.GetString("UpdateNotifier_ForcedUpdate_ProblemDescription", resourceCulture);
            }
        }
        
        internal static string SetupNag_Headline {
            get {
                return ResourceManager.GetString("SetupNag_Headline", resourceCulture);
            }
        }
        
        internal static string SetupNag_ResolutionHelp {
            get {
                return ResourceManager.GetString("SetupNag_ResolutionHelp", resourceCulture);
            }
        }
        
        internal static string SetupNag_AlreadyInstalled_Checklist {
            get {
                return ResourceManager.GetString("SetupNag_AlreadyInstalled_Checklist", resourceCulture);
            }
        }
        
        internal static string SetupNag_AlreadyInstalled_WebSocketHelp {
            get {
                return ResourceManager.GetString("SetupNag_AlreadyInstalled_WebSocketHelp", resourceCulture);
            }
        }
        
        internal static string SetupNag_AlreadyInstalled_ChangeConnectionHelp {
            get {
                return ResourceManager.GetString("SetupNag_AlreadyInstalled_ChangeConnectionHelp", resourceCulture);
            }
        }
        
        internal static string SetupNag_DismissHelp {
            get {
                return ResourceManager.GetString("SetupNag_DismissHelp", resourceCulture);
            }
        }
        
        internal static string CollectionStrategy_CollectionNotFoundError {
            get {
                return ResourceManager.GetString("CollectionStrategy_CollectionNotFoundError", resourceCulture);
            }
        }
        
        internal static string GearsetStrategy_GearsetNotFoundError {
            get {
                return ResourceManager.GetString("GearsetStrategy_GearsetNotFoundError", resourceCulture);
            }
        }
        
        internal static string GeneralActionStrategy_ActionLockedError {
            get {
                return ResourceManager.GetString("GeneralActionStrategy_ActionLockedError", resourceCulture);
            }
        }
        
        internal static string GeneralActionStrategy_ActionIllegalError {
            get {
                return ResourceManager.GetString("GeneralActionStrategy_ActionIllegalError", resourceCulture);
            }
        }
        
        internal static string InstrumentStrategy_PerformanceLockedError {
            get {
                return ResourceManager.GetString("InstrumentStrategy_PerformanceLockedError", resourceCulture);
            }
        }
        
        internal static string InstrumentStrategy_CurrentlyPerformingError {
            get {
                return ResourceManager.GetString("InstrumentStrategy_CurrentlyPerformingError", resourceCulture);
            }
        }
        
        internal static string InstrumentStrategy_InstrumentNotFoundError {
            get {
                return ResourceManager.GetString("InstrumentStrategy_InstrumentNotFoundError", resourceCulture);
            }
        }
        
        internal static string MacroStrategy_MacroEmptyError {
            get {
                return ResourceManager.GetString("MacroStrategy_MacroEmptyError", resourceCulture);
            }
        }
        
        internal static string MacroStrategy_IndividualMacroName {
            get {
                return ResourceManager.GetString("MacroStrategy_IndividualMacroName", resourceCulture);
            }
        }
        
        internal static string MacroStrategy_SharedMacroName {
            get {
                return ResourceManager.GetString("MacroStrategy_SharedMacroName", resourceCulture);
            }
        }
        
        internal static string MainCommandStrategy_ActionInvalidError {
            get {
                return ResourceManager.GetString("MainCommandStrategy_ActionInvalidError", resourceCulture);
            }
        }
        
        internal static string MinionStrategy_MinionNotFoundError {
            get {
                return ResourceManager.GetString("MinionStrategy_MinionNotFoundError", resourceCulture);
            }
        }
        
        internal static string MinionStrategy_MinionLockedError {
            get {
                return ResourceManager.GetString("MinionStrategy_MinionLockedError", resourceCulture);
            }
        }
        
        internal static string MountStrategy_MountNotFoundError {
            get {
                return ResourceManager.GetString("MountStrategy_MountNotFoundError", resourceCulture);
            }
        }
        
        internal static string MountStrategy_MountLockedError {
            get {
                return ResourceManager.GetString("MountStrategy_MountLockedError", resourceCulture);
            }
        }
        
        internal static string OrnamentStrategy_OrnamentLockedError {
            get {
                return ResourceManager.GetString("OrnamentStrategy_OrnamentLockedError", resourceCulture);
            }
        }
        
        internal static string GameClassFactory_NotFoundError {
            get {
                return ResourceManager.GetString("GameClassFactory_NotFoundError", resourceCulture);
            }
        }
        
        internal static string ClassJobService_FallbackClassUsed {
            get {
                return ResourceManager.GetString("ClassJobService_FallbackClassUsed", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_XIVDeckPortOpen {
            get {
                return ResourceManager.GetString("SettingsWindow_XIVDeckPortOpen", resourceCulture);
            }
        }
        
        internal static string SettingsWindow_ListenOnNetwork {
            get {
                return ResourceManager.GetString("SettingsWindow_ListenOnNetwork", resourceCulture);
            }
        }
        
        internal static string UpdateNotifier_TestingUpdate_Headline {
            get {
                return ResourceManager.GetString("UpdateNotifier_TestingUpdate_Headline", resourceCulture);
            }
        }
        
        internal static string UpdateNotifier_TestingUpdate_MismatchDetectedText {
            get {
                return ResourceManager.GetString("UpdateNotifier_TestingUpdate_MismatchDetectedText", resourceCulture);
            }
        }
        
        internal static string UpdateNotifier_TestingUpdate_PleaseTestProperly {
            get {
                return ResourceManager.GetString("UpdateNotifier_TestingUpdate_PleaseTestProperly", resourceCulture);
            }
        }
        
        internal static string UpdateNotifier_TestingUpdate_IgnoreButton {
            get {
                return ResourceManager.GetString("UpdateNotifier_TestingUpdate_IgnoreButton", resourceCulture);
            }
        }
        
        internal static string UpdateNotifier_TestingUpdate_DownloadButton {
            get {
                return ResourceManager.GetString("UpdateNotifier_TestingUpdate_DownloadButton", resourceCulture);
            }
        }
        
        internal static string Common_SupportInfo {
            get {
                return ResourceManager.GetString("Common_SupportInfo", resourceCulture);
            }
        }
        
        internal static string UpdateNotifier_ForcedUpdate_SupportButton {
            get {
                return ResourceManager.GetString("UpdateNotifier_ForcedUpdate_SupportButton", resourceCulture);
            }
        }
        
        internal static string MainCommandStrategy_MainCommandLocked {
            get {
                return ResourceManager.GetString("MainCommandStrategy_MainCommandLocked", resourceCulture);
            }
        }
        
        internal static string SetupNag_HowInstall {
            get {
                return ResourceManager.GetString("SetupNag_HowInstall", resourceCulture);
            }
        }
        
        internal static string SetupNag_HowInstall_Requirements {
            get {
                return ResourceManager.GetString("SetupNag_HowInstall_Requirements", resourceCulture);
            }
        }
        
        internal static string SetupNag_HowInstall_Steps {
            get {
                return ResourceManager.GetString("SetupNag_HowInstall_Steps", resourceCulture);
            }
        }
        
        internal static string SetupNag_HowInstall_OtherInfo {
            get {
                return ResourceManager.GetString("SetupNag_HowInstall_OtherInfo", resourceCulture);
            }
        }
        
        internal static string SetupNag_AlreadyInstalled {
            get {
                return ResourceManager.GetString("SetupNag_AlreadyInstalled", resourceCulture);
            }
        }
        
        internal static string SetupNag_JoinDiscord {
            get {
                return ResourceManager.GetString("SetupNag_JoinDiscord", resourceCulture);
            }
        }
        
        internal static string WebSocketServer_PortInUse_Title {
            get {
                return ResourceManager.GetString("WebSocketServer_PortInUse_Title", resourceCulture);
            }
        }
        
        internal static string WebSocketServer_PortInUse_PortAlreadyInUse {
            get {
                return ResourceManager.GetString("WebSocketServer_PortInUse_PortAlreadyInUse", resourceCulture);
            }
        }
        
        internal static string WebSocketServer_PortInUse_ResolutionInstructions {
            get {
                return ResourceManager.GetString("WebSocketServer_PortInUse_ResolutionInstructions", resourceCulture);
            }
        }
        
        internal static string Common_IgnoreForNowButton {
            get {
                return ResourceManager.GetString("Common_IgnoreForNowButton", resourceCulture);
            }
        }
        
        internal static string TransportManager_TransportUnavailable_Title {
            get {
                return ResourceManager.GetString("TransportManager_TransportUnavailable_Title", resourceCulture);
            }
        }
        
        internal static string TransportManager_TransportUnavailable_Description {
            get {
                return ResourceManager.GetString("TransportManager_TransportUnavailable_Description", resourceCulture);
            }
        }
        
        internal static string TransportManager_TransportUnavailable_ResolutionInstructions {
            get {
                return ResourceManager.GetString("TransportManager_TransportUnavailable_ResolutionInstructions", resourceCulture);
            }
        }
        
        internal static string TransportManager_UdsUnsupported_Title {
            get {
                return ResourceManager.GetString("TransportManager_UdsUnsupported_Title", resourceCulture);
            }
        }
        
        internal static string TransportManager_UdsUnsupported_Description {
            get {
                return ResourceManager.GetString("TransportManager_UdsUnsupported_Description", resourceCulture);
            }
        }
        
        internal static string TransportManager_UdsUnsupported_ResolutionInstructions_Wine {
            get {
                return ResourceManager.GetString("TransportManager_UdsUnsupported_ResolutionInstructions_Wine", resourceCulture);
            }
        }
        
        internal static string TransportManager_UdsUnsupported_ResolutionInstructions_NonWine {
            get {
                return ResourceManager.GetString("TransportManager_UdsUnsupported_ResolutionInstructions_NonWine", resourceCulture);
            }
        }
        
        internal static string TransportManager_UdsUnsupported_SwitchButton {
            get {
                return ResourceManager.GetString("TransportManager_UdsUnsupported_SwitchButton", resourceCulture);
            }
        }
        
        internal static string SetupNag_MessageWillReturn {
            get {
                return ResourceManager.GetString("SetupNag_MessageWillReturn", resourceCulture);
            }
        }
        
        internal static string SetupNag_BypassButton {
            get {
                return ResourceManager.GetString("SetupNag_BypassButton", resourceCulture);
            }
        }
        
        internal static string SetupNag_BypassHint {
            get {
                return ResourceManager.GetString("SetupNag_BypassHint", resourceCulture);
            }
        }
        
        internal static string ConfigService_ConfigReset_Title {
            get {
                return ResourceManager.GetString("ConfigService_ConfigReset_Title", resourceCulture);
            }
        }
        
        internal static string ConfigService_ConfigReset_Description {
            get {
                return ResourceManager.GetString("ConfigService_ConfigReset_Description", resourceCulture);
            }
        }
        
        internal static string GearsetStrategy_InvalidGlamourPlateError {
            get {
                return ResourceManager.GetString("GearsetStrategy_InvalidGlamourPlateError", resourceCulture);
            }
        }
        
        internal static string ChatHelper_MessageEmptyError {
            get {
                return ResourceManager.GetString("ChatHelper_MessageEmptyError", resourceCulture);
            }
        }
        
        internal static string ChatHelper_MessageTooLongError {
            get {
                return ResourceManager.GetString("ChatHelper_MessageTooLongError", resourceCulture);
            }
        }
    }
}
