project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /src/FFXIVPlugin/Resources/Localization/*.resx
    ignore:
      - /src/FFXIVPlugin/Resources/Localization/UIStrings.*.resx
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
  - source: /src/SDPlugin/assets/locales/en/*.json
    translation: /src/SDPlugin/assets/locales/%two_letters_code%/%original_file_name%
    type: i18next_json
