files:
  - source: /FFXIVPlugin/Resources/Localization/*.resx
    ignore:
      - /FFXIVPlugin/Resources/Localization/UIStrings.*.resx
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
