name: Synchronize Crowdin Changes

on:
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Branch Name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: branch
      - name: Update localization
        uses: crowdin/github-action@1.1.0
        with:
          auto_approve_imported: true
          import_eq_suggestions: true
          download_translations: true
          skip_untranslated_strings: true
          export_only_approved: true
          push_translations: true
          commit_message: '[Crowdin] Synchronize Localization Changes'
          create_pull_request: true
          pull_request_title: '[Crowdin] Synchronize Localization Changes'
          pull_request_body: 'Update localization with latest translations from crowdin'
          config: 'crowdin.yml'
          crowdin_branch_name: ${{ steps.branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CROWDIN_PROJECT_ID: ${{secrets.CROWDIN_PROJECT_ID}}
          CROWDIN_PERSONAL_TOKEN: ${{secrets.CROWDIN_PERSONAL_TOKEN}}