name: Upload to Crowdin

on:
  push:
    branches: [ main ]
    paths:
      - 'FFXIVPlugin/Resources/Localization/*.resx'
      - 'SDPlugin/assets/locales/*/*.json'
    
jobs:
  crowdin-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Crowdin Action
        uses: crowdin/github-action@1.4.9
        with:
          upload_sources: true
          upload_translations: true
          download_translations: false
          crowdin_branch_name: ${{ github.ref_name }}
        env:
          CROWDIN_PROJECT_ID: ${{secrets.CROWDIN_PROJECT_ID}}
          CROWDIN_PERSONAL_TOKEN: ${{secrets.CROWDIN_PERSONAL_TOKEN}}