name: Build XIVDeck

on:
  release:
    types: [published]
    
jobs:
  build-ffxivplugin:
    name: Build XIVDeck FFXIV Plugin
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
      - name: Build Plugin
        run: |
          $ver = '${{ github.ref }}' -replace 'refs/tags/v',''
          invoke-expression 'dotnet build --no-restore --configuration Release --nologo -p:AssemblyVersion=$ver -p:Version=$ver -p:FileVersion=$ver FFXIVPlugin'
      - name: Report Build Hash
        run: |
          $fileHashInfo = Get-FileHash .\src\FFXIVPlugin\bin\Release\XIVDeck.FFXIVPlugin\latest.zip;
          Write-Output "Hash of XIVDeck.FFXIVPlugin: $($fileHashInfo.Hash)";
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: XIVDeck.FFXIVPlugin
          path: .\src\FFXIVPlugin\bin\Release\XIVDeck.FFXIVPlugin\

  build-sdplugin:
    name: Build XIVDeck Stream Deck Plugin
    runs-on: ubuntu-latest
    
    defaults: 
      run:
        working-directory: ./src/SDPlugin
    
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn install
      - name: Patch Version
        run: |
          export APP_VERSION=$(echo '${{ github.ref }}' | sed "s!refs/tags/v!!")
          yarn version --new-version $APP_VERSION --no-git-tag-version
      - name: Build for Release
        run: yarn build-release
      - name: Package Plugin
        run: (cd dist && zip -r dev.wolf.xivdeck.streamDeckPlugin dev.wolf.xivdeck.sdPlugin)
      - name: Report Build Hash
        run: echo "[Build Audit] $(sha256sum dist/dev.wolf.xivdeck.streamDeckPlugin)"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: XIVDeck.SDPlugin
          path: ./src/SDPlugin/dist/dev.wolf.xivdeck.streamDeckPlugin
      - name: Add Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./src/SDPlugin/dist/dev.wolf.xivdeck.streamDeckPlugin
          asset_name: XIVDeck.streamDeckPlugin
          asset_content_type: application/zip
          